services:
  web:
    container_name: apache_practica
    image: httpd:latest
    ports:
      - "80:80"
    networks:
      practica_fabulas:
        ipv4_address: 192.168.1.3
    dns:
      - 192.168.1.2
    volumes:
      - /home/oscar/asir2/sri/docker/tareas/Instalaci贸n-de-Apache+Virtual-Host/apache/paginas:/usr/local/apache2/htdocs
      - /home/oscar/asir2/sri/docker/tareas/Instalaci贸n-de-Apache+Virtual-Host/apache/conf:/usr/local/apache2/conf:rw

  DNS:
    container_name: DNS_bind9
    image: ubuntu/bind9
    platform: linux/arm64
    ports:
      - "54:53"
    networks:
      practica_fabulas:
        ipv4_address: 192.168.1.2
    volumes:
      - /home/oscar/asir2/sri/docker/tareas/Instalaci贸n-de-Apache+Virtual-Host/dns/conf:/etc/bind
      - /home/oscar/asir2/sri/docker/tareas/Instalaci贸n-de-Apache+Virtual-Host/dns/zonas:/var/lib/bind
  
  cliente:
    container_name: cliente
    image: ubuntu
    platform: linux/arm64
    tty: true
    stdin_open: true
    dns:
      - 192.168.1.2
    networks:
      practica_fabulas:
        ipv4_address: 192.168.1.4

networks:
  practica_fabulas:
    external: true